### PR TITLE
fix: recognise options that are overwritten unnecessarily

### LINKED ISSUE #7811: VSCode extension: Recognize options that are overwritten unnecessarily
Currently, overwritten options are detected, but if they are overwritten with the exact same options, there is no complaint.

Starting point: `.vscode/extensions/zwave-js-config-editor/src/diagnostics/importOverrideDiagnostics.ts`

### PR DESCRIPTION
**Pull request by SChetwynd**
### Changes:

- Add new util function to compare JSON to AST `isJSONDifferentToAST`.
- Use `isJSONDifferentToAST` function to compare changes after edit.
- Add test files to build when not in production
- Correct import of `Mocha` and `Glob` in test suite

fixes: https://github.com/zwave-js/zwave-js/issues/7811

Options have been overwritten and one of the properties is different, only indicates that the property is overwritten:

image

Options have been overwritten and all of the properties are the same, shows as an error:

image

(^^ I created these examples by changing the `master_template`, those changes are not included in the PR)

### CODE REVIEW

**Comment by SChetwynd** [comment]
The changes I've made to get the tests working might be out of scope for the issue which I'm trying to resolve, so I've structured my commits so that if required I can drop the changes to the test and the new tests and only include the change which resolves the issue. Or I could extract them into a new PR.

File: esbuild.js
Comment (AlCalzone) [inline esbuild.js:1]: I'm not super happy with compiling the test files, given that `node --experimental-strip-types` exists. But getting that to work requires a bunch of changes that are definitely out of scope here, so I'm fine keeping this change.

File: src/astUtils.ts [hunk 1]
```diff
@@ -124,3 +125,64 @@ export function getOptionsFromParamDefinition(
...
+				? "array"
+				: "object"
+			: typeof json;
+
+	if (jsonType !== ast.type) {
+		return true;
+	}
+
+	if (isArrayASTNode(ast) && Array.isArray(json)) {
+		const arrayASTNode = ast;
```
Comment (AlCalzone) [inline src/astUtils.ts]: This assignment just renames `ast` and seems unnecessary.

File: src/astUtils.ts [hunk 2]
```diff
@@ -124,3 +125,64 @@ export function getOptionsFromParamDefinition(
...
+	const jsonType =
+		typeof json === "object"
+			? Array.isArray(json)
+				? "array"
+				: "object"
+			: typeof json;
+
+	if (jsonType !== ast.type) {
+		return true;
+	}
```
Comment (AlCalzone) [inline src/astUtils.ts]: `ast.type` can be `"null"` for the value `null`, so it would make sense to include that in this special handling here.

File: src/astUtils.ts [hunk 3]
```diff
@@ -124,3 +125,64 @@ export function getOptionsFromParamDefinition(
...
+			if (!property.valueNode) {
+				return true;
+			}
+
+			if (
+				isJSONDifferentToAST(
+					(json as Record<string, unknown>)[property.keyNode.value],
+					property.valueNode,
+				)
+			) {
```
Comment (AlCalzone) [inline src/astUtils.ts:171]: I think this is missing the case where the current property exists only in the AST, but not in `json`. Although that is handled in the call due to `typeof json` being `"undefined"`. Please add a comment to avoid having to think about this in the future.

**Review by AlCalzone — CHANGES_REQUESTED** [review]
Just a few nitpicks, otherwise nothing to add

File: src/astUtils.ts (hunk 2 above)
Comment (AlCalzone) [reply src/astUtils.ts]: Ah, nevermind - this is handled. I goofed there.

File: src/astUtils.ts (hunk 1 above)
Comment (SChetwynd) [reply src/astUtils.ts]: Removed.

My bad, originally I used `ast.type === "object"` to check if the AST node was an object type node in the if statement, but typescript wasn't narrowing the types correctly. So I used `const arrayASTNode = ast as ArrayASTNode;` . Which I then refactored into the type guard function, and forgot to remove this line.

File: src/astUtils.ts (hunk 3 above)
Comment (SChetwynd) [reply src/astUtils.ts:171]: I've added a comment for this, and an additional test.

File: src/diagnostics/importOverrideDiagnostics.ts [hunk 4]
```diff
@@ -62,14 +63,13 @@ export function generateImportOverrideDiagnostics(
...
-						[
-							getPropertyNameFromNode(n),
-							getPropertyValueFromNode(n),
-							n,
-						] as const,
-				)
+				.map((n) => {
+					return [
+						getPropertyNameFromNode(n),
+						n.parent.valueNode,
```
[the remark this answers is not in the document]
Comment (AlCalzone) [reply src/diagnostics/importOverrideDiagnostics.ts:69]: Hmm I missed this change. The change itself is fine, so ignore Copilot's review here. Given that the array now contains the AST node and not its value, the variable in line 82 should be renamed to `valueNode`.

File: src/diagnostics/importOverrideDiagnostics.ts [hunk 5]
```diff
@@ -81,9 +81,8 @@ export function generateImportOverrideDiagnostics(
 
 		for (const [name, value, propNode] of properties) {
 			const originalValue = imp[name];
-			const isUnchanged = value === originalValue;
 
-			if (isUnchanged) {
+			if (value && !isJSONDifferentToAST(originalValue, value)) {
```
[the remark this answers is not in the document]
Comment (AlCalzone) [reply src/diagnostics/importOverrideDiagnostics.ts]: This nitpick seems correct, please change.

File: src/diagnostics/importOverrideDiagnostics.ts [hunk 6]
```diff
@@ -81,9 +81,8 @@ export function generateImportOverrideDiagnostics(
...
 				ret.push({
 					type: DiagnosticType.UnnecessaryImportOverride,
 					range: rangeFromNode(config.original, propNode.parent),
```
Comment (AlCalzone) [inline src/diagnostics/importOverrideDiagnostics.ts:88]: Also now in line 94 (?) the `value` property for the diagnostic should be `valueNode?.value`, not the AST node.

**Review by AlCalzone — CHANGES_REQUESTED** [review]
@SChetwynd Sorry, there are a few more things I missed. I already committed the spelling fixes, so make sure to pull first.

The comments are referring to the Copilot review comments above, in case the context is not clear.

File: src/diagnostics/importOverrideDiagnostics.ts (hunk 5 above)
[the remark this answers is not in the document]
Comment (SChetwynd) [reply src/diagnostics/importOverrideDiagnostics.ts]: Typescript complains when I make this change, `value` is set to `n.parent.valueNode`, and `n.parent` is typed as an `ASTNode` which doesn't always have a `valueNode` even if logically it must have one.

I could change the `isJSONDifferentToAST` to accept `undefined` as the second param, which would remove the need to check if the value is defined here.

File: src/diagnostics/importOverrideDiagnostics.ts (hunk 4 above)
[the remark this answers is not in the document]
Comment (SChetwynd) [reply src/diagnostics/importOverrideDiagnostics.ts:69]: I'm wondering if the array could be reduced to just the property name , and the ASTNode. 

Line 94 could be changed to: `value: getPropertyValueFromNode(propNode),`.

And line 85 to `if (!isJSONDifferentToAST(originalValue, propNode.parent.valueNode))`

File: src/diagnostics/importOverrideDiagnostics.ts (hunk 5 above)
[the remark this answers is not in the document]
Comment (AlCalzone) [reply src/diagnostics/importOverrideDiagnostics.ts]: Ok, let's keep this one as is then.

File: src/diagnostics/importOverrideDiagnostics.ts (hunk 4 above)
[the remark this answers is not in the document]
Comment (AlCalzone) [reply src/diagnostics/importOverrideDiagnostics.ts:69]: Hmm that wouldn't change the other type issue with the value possibly being undefined. Let's just stick to renaming then and making sure we pass the actual value to the diagnostic and not the AST node (see other comment).

File: src/diagnostics/importOverrideDiagnostics.ts (hunk 6 above)
Comment (SChetwynd) [reply src/diagnostics/importOverrideDiagnostics.ts:88]: I've changed line 94 to use the `getPropertyValueFromNode` function which was originally used to get the value.

File: src/diagnostics/importOverrideDiagnostics.ts (hunk 4 above)
[the remark this answers is not in the document]
Comment (SChetwynd) [reply src/diagnostics/importOverrideDiagnostics.ts:69]: I've changed the variable name as suggested

**Review by AlCalzone — APPROVED** [review]
Thanks a lot!
